"""Reference vanilla item textures; read client pixels only to calculate glyph advances."""
from pathlib import Path
import argparse
import io
import json
import zipfile
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ICONS = ("diamond", "emerald", "book", "ender_pearl", "golden_apple", "nether_star")


def build(client_jar):
    providers = [{"type": "space", "advances": {"\ue000": -3145728, "\ue001": 3145728}}]
    metrics = ["# Generated by tools/build_animation_icons.py; vanilla bitmap advance rounding."]
    with zipfile.ZipFile(client_jar) as client:
        version = json.loads(client.read("version.json"))["id"]
        if version not in ("26.2", "26.3"):
            raise ValueError(f"Expected supported vanilla client 26.2 or 26.3, got {version}")
        for index, name in enumerate(ICONS):
            texture = f"assets/minecraft/textures/item/{name}.png"
            with Image.open(io.BytesIO(client.read(texture))) as image:
                assert image.size == (16, 16), (texture, image.size)
                right = image.convert("RGBA").getchannel("A").getbbox()[2]
            codepoint = 0xE100 + index
            providers.append({"type": "bitmap", "file": f"minecraft:item/{name}.png",
                              "height": 36, "ascent": 7, "chars": [chr(codepoint)]})
            metrics.append(f"glyph.{codepoint}={int(right * 36 / 16 + .5) + 1}")
    font = ROOT / "resourcepack/assets/dialogmenu_animation/font/icons.json"
    font.parent.mkdir(parents=True, exist_ok=True)
    font.write_text(json.dumps({"providers": providers}, ensure_ascii=True, indent=2) + "\n", encoding="utf-8")
    (ROOT / "src/main/resources/animation-icons.properties").write_text("\n".join(metrics) + "\n", encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--client-jar", type=Path, required=True, help="Supported vanilla Minecraft client JAR")
    build(parser.parse_args().client_jar)
