"""Reference the client's Unicode font and compile exact advances, including half pixels.

Run after rebuilding any label bitmap fonts. Requires Pillow only at build time.
"""
from pathlib import Path
import hashlib
import json
import math
import zipfile
from functools import cache
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'resourcepack/assets'
FONT = ASSETS / 'dialogmenu_settings/font'
UNIFONT_SOURCE = ROOT / 'design/minecraft-font/unifont.zip'
# Minecraft 26.2 asset minecraft/font/unifont.zip; revalidate when upgrading clients.
UNIFONT_SHA256 = 'aea3e9918b0d31de6f94623080f04c31c8c16a5b1a2e8d99ab39f1acdddd30f7'
OVERRIDES = [(0x3001,0x30FF,0,15), (0x3200,0x9FFF,0,15),
             (0x1100,0x11FF,0,15), (0x3130,0x318F,0,15),
             (0xA960,0xA97F,0,15), (0xD7B0,0xD7FF,0,15),
             (0xAC00,0xD7AF,1,15), (0xF900,0xFAFF,0,15),
             (0xFF01,0xFF5E,0,15)]


def write_generated(path, text):
    # Avoid rewriting unchanged metrics/UI assets, including their existing line endings.
    if path.exists() and path.read_text(encoding='utf-8') == text:
        return
    path.write_text(text, encoding='utf-8', newline='\n')


def compile_metrics():
    if hashlib.sha256(UNIFONT_SOURCE.read_bytes()).hexdigest() != UNIFONT_SHA256:
        raise ValueError('Design Unicode font differs from the verified Minecraft 26.2 asset')
    legacy_archive = FONT / 'unifont.zip'
    if legacy_archive.exists() and hashlib.sha256(legacy_archive.read_bytes()).hexdigest() != UNIFONT_SHA256:
        raise ValueError('Refusing to remove a modified resourcepack/font/unifont.zip')
    provider = {'type':'unihex', 'hex_file':'minecraft:font/unifont.zip',
                'size_overrides':[{'from':chr(a), 'to':chr(b), 'left':l, 'right':r}
                                  for a,b,l,r in OVERRIDES]}
    write_generated(FONT / 'unifont.json', json.dumps({'providers':[provider]}) + '\n')
    unicode = {}
    with zipfile.ZipFile(UNIFONT_SOURCE) as archive:
        for name in archive.namelist():
            if not name.endswith('.hex'):
                continue
            for line in archive.read(name).decode().splitlines():
                code, bits = line.split(':')
                cp = int(code, 16)
                digits = len(bits) // 16
                mask = 0
                for i in range(0, len(bits), digits):
                    mask |= int(bits[i:i+digits],16)
                # Minecraft uses inclusive bounds [0, bitWidth] for an empty glyph.
                width = mask.bit_length() - ((mask & -mask).bit_length()-1) if mask else digits*4+1
                for start,end,left,right in OVERRIDES:
                    if start <= cp <= end:
                        width = right-left+1
                        break
                unicode[cp] = (width/2+1, 0.5)

    @cache
    def read_font(key):
        namespace, name = key.split(':')
        if key == 'dialogmenu_settings:unifont':
            return unicode.copy()
        path = ASSETS / namespace / 'font' / (name + '.json')
        data = json.loads(path.read_text(encoding='utf-8'))
        result = {}
        for entry in reversed(data['providers']):
            kind = entry['type']
            if kind == 'reference':
                result.update(read_font(entry['id']))
            elif kind == 'space':
                result.update({ord(c):(w,1) for c,w in entry['advances'].items()})
            elif kind == 'bitmap':
                ns, file = entry['file'].split(':')
                with Image.open(ASSETS / ns / 'textures' / file) as raw:
                    img = raw.convert('RGBA')
                    rows = entry['chars']
                    cw, ch = img.width//len(rows[0]), img.height//len(rows)
                    scale = entry.get('height',8)/ch
                    for y,row in enumerate(rows):
                        for x,c in enumerate(row):
                            if c == '\0':
                                continue
                            bounds = img.crop((x*cw,y*ch,(x+1)*cw,(y+1)*ch)).getchannel('A').getbbox()
                            ink = bounds[2] if bounds else 0
                            result[ord(c)] = (math.floor(ink*scale+0.5)+1, 1)
            else:
                raise ValueError(kind)
        return result

    lines = ['# font start end advance bold-offset; generated by tools/build_label_metrics.py']
    for namespace in ['dialogmenu_settings','dialogmenu_dialogue']:
        for name in ['labels','button_labels']:
            key = f'{namespace}:{name}'
            glyphs = read_font(key)
            parent = None if key == 'dialogmenu_settings:labels' else (
                'dialogmenu_settings:button_labels' if key == 'dialogmenu_dialogue:button_labels'
                else 'dialogmenu_settings:labels')
            lines.append(f'@ {key} {parent or "-"}')
            if parent:
                base = read_font(parent)
                glyphs = {cp:value for cp,value in glyphs.items() if base.get(cp) != value}
            start = end = -1
            previous = None
            for cp, value in sorted(glyphs.items()):
                if cp == end+1 and value == previous:
                    end = cp
                    continue
                if previous is not None:
                    lines.append(f'{key} {start} {end} {previous[0]:g} {previous[1]:g}')
                start = end = cp
                previous = value
            if previous is not None:
                lines.append(f'{key} {start} {end} {previous[0]:g} {previous[1]:g}')
    write_generated(ROOT / 'src/main/resources/label-metrics.txt', '\n'.join(lines)+'\n')
    ui_path = FONT / 'ui.json'
    ui = json.loads(ui_path.read_text(encoding='utf-8'))
    spaces = next(p['advances'] for p in ui['providers'] if p['type'] == 'space')
    spaces.update({'\ue7f0':0.5, '\ue7f1':-0.5})
    write_generated(ui_path, json.dumps(ui, separators=(',',':'))+'\n')
    legacy_archive.unlink(missing_ok=True)
    print(f'Compiled {len(lines)-1} font ranges; coin advance={unicode[0x26C2][0]}')


if __name__ == '__main__':
    compile_metrics()
